Wrap lines
GIScience/ohsome-api pull request #148
Opened 2021-03-08 14:34 UTC by bonaparten

Please add the **type of change** as label. If your PR is not ready for review and merge, please add `🚧 ` to the PR title.

### Description
Please add a clear and concise description of what your PR solves.

### Corresponding issue
Closes #

### New or changed dependencies
-

### Checklist
- [ ] My code follows the [code-style](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#code-style) rules, and I have checked on the [static analyses](https://jenkins.ohsome.org/job/ohsome-api/view/change-requests/)
- [ ] I have commented my code
- [ ] I have written javadoc (required for public methods)
- [ ] I have added sufficient unit and API tests
- [ ] I have made corresponding changes to the [documentation](https://github.com/GIScience/ohsome-api/tree/master/docs)
- [ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-api/blob/master/CHANGELOG.md)
- [ ] I have adjusted the examples in the [check-ohsome-api](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api) script or [created an issue](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api/-/issues/new) in the corresponding repository. More Information [here](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#check-examples).

Please check all finished tasks. If some tasks do not apply to your PR, please cross their text out (by using `~...~`) and remove their checkboxes.

2021-03-10 11:31 UTC, tyrasd requested changes
I marked a few spots where this change introduces trailing whitespaces (i.e. a superfluous space ` ` at the end of a line), but didn't mark all of them because there were so many :see_no_evil: . Normally, IDEs remove those automatically during save, maybe yours doesn't?!

I can still see 6 lines over 100 characters. https://jenkins.ohsome.org/job/ohsome-api/view/change-requests/job/PR-148/4/checkstyle/type.-1710651122/#issuesContent
It seems like a good moment to fix these as well.

2021-03-10 11:31 UTC, tyrasd commented on src/main/lombok/org/heigit/ohsome/ohsomeapi/Application.java
> +   * @throws RuntimeException if database and keytables are not defined in the
trailing whitespaces should be avoided

2021-03-10 11:31 UTC, tyrasd commented on CHANGELOG.md
> +* wrap all lines longer than 100 characters ([#83])
maybe to make it clear that it's about the code lines (and not the output json/csv lines for example):

```suggestion
* improve code style by wrapping all code lines longer than 100 characters ([#83])
```

2021-03-10 11:31 UTC, tyrasd commented on src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/AreaController.java
> +   *         #aggregateGroupByKey(RequestResource, HttpServletRequest, HttpServletResponse,
trailing whitespace

2021-03-10 11:31 UTC, tyrasd commented on src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/AreaController.java
> +   *         #aggregateGroupByTag(RequestResource, HttpServletRequest, HttpServletResponse,
trailing whitespace

2021-03-10 11:31 UTC, tyrasd commented on src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/AreaController.java
> +   *         #aggregateGroupByType(RequestResource, HttpServletRequest, HttpServletResponse,
trailing space

2021-03-11 10:04 UTC, bonaparten commented
> I can still see 6 lines over 100 characters. https://jenkins.ohsome.org/job/ohsome-api/view/change-requests/job/PR-148/4/checkstyle/type.-1710651122/#issuesContent
> It seems like a good moment to fix these as well.

Two of them are in commented tests. I have to uncomment the tests and check if they work. I will do that in another PR.

2021-03-11 10:11 UTC, tyrasd approved these changes

2021-03-11 10:24 UTC, merged