apply geometry checks to all stages in elementsFullHistory requests
GIScience/ohsome-api pull request #151
Opened 2021-03-17 17:01 UTC by tyrasd

### Description
Updates `addEntityToOutput` method to check geometry filters not only in the deprecated "simpleFeatureTypes" code path.

### Corresponding issue
Closes #109 

### Checklist
- [ ] My code follows the [code-style](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#code-style) rules, and I have checked on the [static analyses](https://jenkins.ohsome.org/job/ohsome-api/view/change-requests/)
- [ ] I have commented my code
- [ ] I have written javadoc (required for public methods)
- [ ] I have added sufficient unit and API tests
- [ ] I have made corresponding changes to the [documentation](https://github.com/GIScience/ohsome-api/tree/master/docs)
- [ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-api/blob/master/CHANGELOG.md)
- [ ] I have adjusted the examples in the [check-ohsome-api](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api) script or [created an issue](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api/-/issues/new) in the corresponding repository. More Information [here](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#check-examples).

Please check all finished tasks. If some tasks do not apply to your PR, please cross their text out (by using `~...~`) and remove their checkboxes.

2021-03-17 18:46 UTC, tyrasd commented
strictly speaking, cd57e8a9360b8ad15426496b2b3ed8ca73fd659c is unrelated to #109, but I thought it might still be nice to have all defined tests to be executed on jenkins :wink:

2021-03-18 08:49 UTC, FabiKo117 commented
> strictly speaking, [cd57e8a](https://github.com/GIScience/ohsome-api/commit/cd57e8a9360b8ad15426496b2b3ed8ca73fd659c) is unrelated to #109, but I thought it might still be nice to have all defined tests to be executed on jenkins 😉

You mean jenkins only executes tests that have explicitly `Test` written in the method name..? :O

2021-03-18 09:11 UTC, tyrasd commented
> > strictly speaking, [cd57e8a](https://github.com/GIScience/ohsome-api/commit/cd57e8a9360b8ad15426496b2b3ed8ca73fd659c) is unrelated to #109, but I thought it might still be nice to have all defined tests to be executed on jenkins wink
> 
> You mean jenkins only executes tests that have explicitly `Test` written in the method name..? :O

Oh, forget what I wrote. I miscounted the tests that should be executed and falsely remembered that test methods should have the same naming scheme as the test classes (see https://stackoverflow.com/a/6178629/1627467). Actually, this doesn't apply to the method names, so it was already fine. I would say we still keep the changes from cd57e8a, since it makes all test method have a uniform naming scheme.

2021-03-18 09:30 UTC, FabiKo117 requested changes
Please check the comments.

2021-03-18 09:34 UTC, tyrasd commented on src/test/java/org/heigit/ohsome/ohsomeapi/controller/DataExtractionTest.java
> +    assertEquals(1, response.getBody().get("features").size());
> 2nd one with the broken `LineString`

Wasn't the second (falsely returned) feature a `GeometryCollection`?

> I'd say that this test should also work on the /geometry endpoint then, as it's not clear here that this test works when using /centroid.

I used the `/centroid` endpoint on purpose to check if my fix also applies to transformed geometries, not just in the "pure" `/geometry` version. I assume that if it works for the more elaborate endpoint, it certainly will also work with the regular version.

2021-03-18 10:04 UTC, FabiKo117 commented
> > You mean jenkins only executes tests that have explicitly `Test` written in the method name..? :O
> 
> Oh, forget what I wrote. I miscounted the tests that should be executed and falsely remembered that test methods should have the same naming scheme as the test classes (see https://stackoverflow.com/a/6178629/1627467). Actually, this doesn't apply to the method names, so it was already working fine and didn't need a _fix_. I would say we still keep the changes from [cd57e8a](https://github.com/GIScience/ohsome-api/commit/cd57e8a9360b8ad15426496b2b3ed8ca73fd659c) (now [b3d5112](https://github.com/GIScience/ohsome-api/commit/b3d51120f6204976b454d76971dc1af313a51c4a)), since it makes all test method have a uniform naming scheme.

Ok I see.. Since it's only important for the classes to follow the specific format, my idea was to remove then the superfluous `Test` at the end of every method. That's why I did not add it to the new tests. And I did not want to change all test names within that branch. Should have created an issue for that I guess so it would not get forgotten..

2021-03-18 10:11 UTC, FabiKo117 approved these changes

2021-03-18 10:17 UTC, merged