WIP: Adapting ratio endpoint
GIScience/ohsome-api pull request #27
Opened 2020-08-18 12:17 UTC by FabiKo117

- [ ] filter2 param can be null or empty (needs an adaption in the ohsome-filter library as well)

- [ ] filter param has to be defined - throws exception if param is null or empty

- [ ] marking types-keys-values code handling /ratio requests as deprecated

2020-08-27 15:21 UTC, tyrasd requested changes
this needs some unit tests to check if the behaviour for empty filters is correct. While testing I discovered that an empty `filter2` with a share request does not work because the API internally converts such a query to something like `(<filter1>) or ()` (see screenshot below), which is not a valid filter syntax.

![image](https://user-images.githubusercontent.com/1927298/91461909-ddf1db00-e889-11ea-9f2d-7b0bc355937d.png)

2020-08-27 16:07 UTC, FabiKo117 commented
You found this behavior with a /share request? The resource "/share" is not supported anymore since the release 1.0 from what I know.

2020-08-28 06:53 UTC, FabiKo117 commented
Ok I could reproduce it. Working on it now.

2020-08-28 06:53 UTC, tyrasd commented
sorry, I meant it happens in a `ratio` request (as you can see in the screenshot) :sweat_smile: .  here is an example request and output:

```
$ curl "localhost:8082/elements/count/ratio?bboxes=8.6906,49.3994,8.6962,49.4032&filter=building=*&filter2="
{
  "timestamp" : "2020-08-27T16:38:17.077418",
  "status" : 400,
  "message" : "Invalid filter syntax. Please look at the additional info and examples about the filter parameter at https://docs.ohsome.org/ohsome-api. Detailed error message: line 1, column 18: whitespaces, not, (, KEY_STRING (a-z, 0-9, : or -), \", id, type or geometry expected, ) encountered.",
  "requestUrl" : "http://localhost:8082/elements/count/ratio?bboxes=8.6906,49.3994,8.6962,49.4032&filter=building=*&filter2="
}
```

2020-09-01 10:56 UTC, tyrasd reviewed
I would have preferred if the `filter2` parameter was not optional for ratio requests, so that users don't by mistake send complex, long-running queries if they just alter an existing `/count/` query to a `/count/share/` one without thinking to add the `filter2` parameter (I know I would probably often make this mistake). It would still be possible to leave the `filter2` parameter empty to do the _"compare against all OSM data"_ use case. But if you prefer it this way @FabiKo117 I am willing to accept it as is.

2020-09-01 14:07 UTC, FabiKo117 commented
Ahh yeah I get that point. If someone is just playing around with the endpoints using the same set of parameters, defining filter2 as being non-optional for /ratio would avoid that issue with requesting too much data unintentionally. We can switch that restriction yes.

2020-09-02 08:28 UTC, tyrasd approved these changes

2020-09-02 09:59 UTC, merged